using Ankama.Cube.Protocols.CommonProtocol;
using Ankama.Cube.Protocols.FightCommonProtocol;
using Google.Protobuf.Reflection;
using Google.Protobuf.WellKnownTypes;
using System;

namespace Ankama.Cube.Fight.Events
{
	public static class EventsReflection
	{
		private static FileDescriptor descriptor;

		public static FileDescriptor Descriptor => descriptor;

		static EventsReflection()
		{
			//IL_0372: Unknown result type (might be due to invalid IL or missing references)
			//IL_0378: Expected O, but got Unknown
			//IL_0378: Unknown result type (might be due to invalid IL or missing references)
			//IL_0382: Expected O, but got Unknown
			descriptor = FileDescriptor.FromGeneratedCode(Convert.FromBase64String("CgxldmVudHMucHJvdG8SBmV2ZW50cxoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBw" + "ZXJzLnByb3RvGhRjb21tb25Qcm90b2NvbC5wcm90bxoZZmlnaHRDb21tb25Q" + "cm90b2NvbC5wcm90byLXEwoORmlnaHRFdmVudERhdGESMwoJZXZlbnRUeXBl" + "GAEgASgOMiAuZXZlbnRzLkZpZ2h0RXZlbnREYXRhLkV2ZW50VHlwZRIPCgdl" + "dmVudElkGAIgASgREjIKDXBhcmVudEV2ZW50SWQYAyABKAsyGy5nb29nbGUu" + "cHJvdG9idWYuSW50MzJWYWx1ZRIMCgRpbnQxGAQgASgFEgwKBGludDIYBSAB" + "KAUSDAoEaW50MxgGIAEoBRIMCgRpbnQ0GAcgASgFEgwKBGludDUYCCABKAUS" + "DAoEaW50NhgJIAEoBRIMCgRpbnQ3GAogASgFEg8KB3N0cmluZzEYCyABKAkS" + "DQoFYm9vbDEYDCABKAgSHgoKY2VsbENvb3JkMRgNIAEoCzIKLkNlbGxDb29y" + "ZBIeCgpjZWxsQ29vcmQyGA4gASgLMgouQ2VsbENvb3JkEjYKFmNvbXBhbmlv" + "blJlc2VydmVTdGF0ZTEYDyABKA4yFi5Db21wYW5pb25SZXNlcnZlU3RhdGUS" + "NgoWY29tcGFuaW9uUmVzZXJ2ZVN0YXRlMhgQIAEoDjIWLkNvbXBhbmlvblJl" + "c2VydmVTdGF0ZRIyChRkYW1hZ2VSZWR1Y3Rpb25UeXBlMRgRIAEoDjIULkRh" + "bWFnZVJlZHVjdGlvblR5cGUSIgoMZmlnaHRSZXN1bHQxGBIgASgOMgwuRmln" + "aHRSZXN1bHQSKAoPZ2FtZVN0YXRpc3RpY3MxGBMgASgLMg8uR2FtZVN0YXRp" + "c3RpY3MSRAoddGVhbXNTY29yZU1vZGlmaWNhdGlvblJlYXNvbjEYFCABKA4y" + "HS5UZWFtc1Njb3JlTW9kaWZpY2F0aW9uUmVhc29uEiwKB29wdEludDEYFSAB" + "KAsyGy5nb29nbGUucHJvdG9idWYuSW50MzJWYWx1ZRIsCgdvcHRJbnQyGBYg" + "ASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUSLAoHb3B0SW50MxgX" + "IAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlEiwKB29wdEludDQY" + "GCABKAsyGy5nb29nbGUucHJvdG9idWYuSW50MzJWYWx1ZRIiCg5jZWxsQ29v" + "cmRMaXN0MRgZIAMoCzIKLkNlbGxDb29yZBIqChJzcGVsbE1vdmVtZW50TGlz" + "dDEYGiADKAsyDi5TcGVsbE1vdmVtZW50EiQKD2Nhc3RUYXJnZXRMaXN0MRgb" + "IAMoCzILLkNhc3RUYXJnZXQSEAoIaW50TGlzdDEYHCADKAUSEAoIaW50TGlz" + "dDIYHSADKAUi/gsKCUV2ZW50VHlwZRISCg5FRkZFQ1RfU1RPUFBFRBAAEhAK" + "DFRVUk5fU1RBUlRFRBACEhUKEUVOVElUWV9BUkVBX01PVkVEEAMSEAoMUExB" + "WUVSX0FEREVEEAQSDgoKSEVST19BRERFRBAFEhMKD0NPTVBBTklPTl9BRERF" + "RBAGEhMKD0VOVElUWV9BQ1RJT05FRBAHEhAKDFNQRUxMU19NT1ZFRBAIEhMK" + "D1RFQU1fVFVSTl9FTkRFRBAJEg4KClBMQVlfU1BFTEwQChIOCgpUVVJOX0VO" + "REVEEAsSGAoUQVJNT1JFRF9MSUZFX0NIQU5HRUQQDBISCg5FTlRJVFlfUkVN" + "T1ZFRBANEhoKFkVMRU1FTlRfUE9JTlRTX0NIQU5HRUQQDhIeChpDT01QQU5J" + "T05fQURERURfSU5fUkVTRVJWRRAPEhkKFUFDVElPTl9QT0lOVFNfQ0hBTkdF" + "RBAQEiMKH0NPTVBBTklPTl9SRVNFUlZFX1NUQVRFX0NIQU5HRUQQERIbChdF" + "TlRJVFlfUFJPVEVDVElPTl9BRERFRBASEh0KGUVOVElUWV9QUk9URUNUSU9O" + "X1JFTU9WRUQQExIjCh9NQUdJQ0FMX0RBTUFHRV9NT0RJRklFUl9DSEFOR0VE" + "EBQSIQodTUFHSUNBTF9IRUFMX01PRElGSUVSX0NIQU5HRUQQFRIbChdNT1ZF" + "TUVOVF9QT0lOVFNfQ0hBTkdFRBAWEg8KC0RJQ0VfVEhST1dOEBgSEwoPU1VN" + "TU9OSU5HX0FEREVEEBkSFwoTRU5USVRZX0FDVElPTl9SRVNFVBAaEhoKFlJF" + "U0VSVkVfUE9JTlRTX0NIQU5HRUQQGxIQCgxSRVNFUlZFX1VTRUQQHBIUChBQ" + "Uk9QRVJUWV9DSEFOR0VEEB0SGQoVRkxPT1JfTUVDSEFOSVNNX0FEREVEEB4S" + "HgoaRkxPT1JfTUVDSEFOSVNNX0FDVElWQVRJT04QHxIaChZPQkpFQ1RfTUVD" + "SEFOSVNNX0FEREVEECASHQoZU1BFTExfQ09TVF9NT0RJRklFUl9BRERFRBAh" + "Eh8KG1NQRUxMX0NPU1RfTU9ESUZJRVJfUkVNT1ZFRBAiEg4KClRFQU1fQURE" + "RUQQIxIPCgtGSUdIVF9FTkRFRBAkEhIKDlRSQU5TRk9STUFUSU9OECUSFgoS" + "RUxFTUVOVEFSWV9DSEFOR0VEECYSEgoOREFNQUdFX1JFRFVDRUQQJxIKCgZB" + "VFRBQ0sQKBINCglFWFBMT1NJT04QKRIUChBFTlRJVFlfQU5JTUFUSU9OECoS" + "FwoTRU5USVRZX1NLSU5fQ0hBTkdFRBArEiIKHkZMT0FUSU5HX0NPVU5URVJf" + "VkFMVUVfQ0hBTkdFRBAsEhYKEkFTU0VNQkxBR0VfQ0hBTkdFRBAtEiQKIFBI" + "WVNJQ0FMX0RBTUFHRV9NT0RJRklFUl9DSEFOR0VEEC4SIgoeUEhZU0lDQUxf" + "SEVBTF9NT0RJRklFUl9DSEFOR0VEEC8SGwoXQk9TU19TVU1NT05JTkdTX1dB" + "Uk5JTkcQMBIdChlCT1NTX1JFU0VSVkVfTU9ESUZJQ0FUSU9OEDESJAogQk9T" + "U19FVk9MVVRJT05fU1RFUF9NT0RJRklDQVRJT04QMhITCg9CT1NTX1RVUk5f" + "U1RBUlQQMxIaChZCT1NTX0xJRkVfTU9ESUZJQ0FUSU9OEDQSEwoPQk9TU19D" + "QVNUX1NQRUxMEDUSDgoKR0FNRV9FTkRFRBA2EhMKD0NPTVBBTklPTl9HSVZF" + "ThA3EhYKEkNPTVBBTklPTl9SRUNFSVZFRBA4EhUKEVRFQU1fVFVSTl9TVEFS" + "VEVEEDkSEQoNQk9TU19UVVJOX0VORBA6EhgKFFRVUk5fU1lOQ0hST05JWkFU" + "SU9OEDsSFwoTRVZFTlRfRk9SX1BBUkVOVElORxA8EhwKGFRFQU1TX1NDT1JF" + "X01PRElGSUNBVElPThA9EhQKEE1BWF9MSUZFX0NIQU5HRUQQPhIVChFGSUdI" + "VF9JTklUSUFMSVpFRBA/QjIKFWNvbS5hbmthbWEuY3ViZS5wcm90b6oCGEFu" + "a2FtYS5DdWJlLkZpZ2h0LkV2ZW50c2IGcHJvdG8z"), (FileDescriptor[])new FileDescriptor[3]
			{
				WrappersReflection.get_Descriptor(),
				CommonProtocolReflection.Descriptor,
				FightCommonProtocolReflection.Descriptor
			}, new GeneratedClrTypeInfo((Type[])null, (GeneratedClrTypeInfo[])new GeneratedClrTypeInfo[1]
			{
				new GeneratedClrTypeInfo(typeof(FightEventData), FightEventData.Parser, new string[29]
				{
					"EventType",
					"EventId",
					"ParentEventId",
					"Int1",
					"Int2",
					"Int3",
					"Int4",
					"Int5",
					"Int6",
					"Int7",
					"String1",
					"Bool1",
					"CellCoord1",
					"CellCoord2",
					"CompanionReserveState1",
					"CompanionReserveState2",
					"DamageReductionType1",
					"FightResult1",
					"GameStatistics1",
					"TeamsScoreModificationReason1",
					"OptInt1",
					"OptInt2",
					"OptInt3",
					"OptInt4",
					"CellCoordList1",
					"SpellMovementList1",
					"CastTargetList1",
					"IntList1",
					"IntList2"
				}, (string[])null, new Type[1]
				{
					typeof(FightEventData.Types.EventType)
				}, (GeneratedClrTypeInfo[])null)
			}));
		}
	}
}
