namespace Ankama.Cube.Data
{
	public enum God
	{
		None,
		[BundleName("iops")]
		Iop,
		[BundleName("cras")]
		Cra,
		[BundleName("eniripsas")]
		Eniripsa,
		[BundleName("ecaflips")]
		Ecaflip,
		[BundleName("enutrofs")]
		Enutrof,
		[BundleName("srams")]
		Sram,
		[BundleName("xelors")]
		Xelor,
		[BundleName("sacrieurs")]
		Sacrieur,
		[BundleName("fecas")]
		Feca,
		[BundleName("sadidas")]
		Sadida,
		[BundleName("osamodas")]
		Osamodas,
		[BundleName("pandawas")]
		Pandawa
	}
}
