namespace Ankama.Cube.Fight
{
	public enum CastValidity
	{
		SUCCESS,
		NO_TARGET_AVAILABLE,
		NOT_ENOUGH_ACTION_POINTS,
		NOT_ENOUGH_ELEMENT_POINTS,
		NOT_ENOUGH_RESERVE_POINTS,
		NOT_ALLOW_TO_PLAY_SPELLS,
		TOO_MANY_SUMMONING,
		TOO_MANY_MECHANISM,
		DATA_ERROR
	}
}
